package com.fnwcs.pda.app.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.fnwcs.pda.app.model.DbComUsraut;

@Mapper
public interface DbComUsrautMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_USRAUT
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(@Param("uaUsid") String uaUsid, @Param("uaMnid") String uaMnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_USRAUT
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(DbComUsraut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_USRAUT
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    DbComUsraut selectByPrimaryKey(@Param("uaUsid") String uaUsid, @Param("uaMnid") String uaMnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_USRAUT
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<DbComUsraut> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_USRAUT
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(DbComUsraut record);
}