package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.DbComCode;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbComCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_CODE
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(@Param("classCode") String classCode, @Param("comCode") String comCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_CODE
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(DbComCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_CODE
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    DbComCode selectByPrimaryKey(@Param("classCode") String classCode, @Param("comCode") String comCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_CODE
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<DbComCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_CODE
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(DbComCode record);
}