package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.DbComEqucom;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbComEqucomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_EQUCOM
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(@Param("equComEquip") String equComEquip, @Param("equComEqno") String equComEqno, @Param("equComKind") String equComKind);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_EQUCOM
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(DbComEqucom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_EQUCOM
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    DbComEqucom selectByPrimaryKey(@Param("equComEquip") String equComEquip, @Param("equComEqno") String equComEqno, @Param("equComKind") String equComKind);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_EQUCOM
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<DbComEqucom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_COM_EQUCOM
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(DbComEqucom record);
}