package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.DbCrcJobmst;
import java.util.List;

public interface DbCrcJobmstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_CRC_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(String jobNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_CRC_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(DbCrcJobmst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_CRC_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    DbCrcJobmst selectByPrimaryKey(String jobNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_CRC_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<DbCrcJobmst> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_CRC_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(DbCrcJobmst record);
}