package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.DbStoStodtl;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbStoStodtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STODTL
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(@Param("whid") String whid, @Param("loct") String loct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STODTL
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(DbStoStodtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STODTL
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    DbStoStodtl selectByPrimaryKey(@Param("whid") String whid, @Param("loct") String loct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STODTL
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<DbStoStodtl> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STODTL
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(DbStoStodtl record);
}