package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.DbStoStomst;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbStoStomstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STOMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(@Param("whid") String whid, @Param("loct") String loct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STOMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(DbStoStomst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STOMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    DbStoStomst selectByPrimaryKey(@Param("whid") String whid, @Param("loct") String loct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STOMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<DbStoStomst> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_STO_STOMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(DbStoStomst record);
}