package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.DbSysClchst;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbSysClchstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_CLCHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(@Param("hstDtm") Date hstDtm, @Param("taskky") String taskky, @Param("skukey") String skukey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_CLCHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(DbSysClchst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_CLCHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    DbSysClchst selectByPrimaryKey(@Param("hstDtm") Date hstDtm, @Param("taskky") String taskky, @Param("skukey") String skukey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_CLCHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<DbSysClchst> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_CLCHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(DbSysClchst record);
}