package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.DbSysJobmst;
import java.util.List;

public interface DbSysJobmstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(String jobNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(DbSysJobmst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    DbSysJobmst selectByPrimaryKey(String jobNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<DbSysJobmst> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBMST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(DbSysJobmst record);
}