package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.DbSysJobhst;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbSysJobhstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(@Param("hstDtm") Date hstDtm, @Param("bcrPos") String bcrPos, @Param("invNo") String invNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(DbSysJobhst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    DbSysJobhst selectByPrimaryKey(@Param("hstDtm") Date hstDtm, @Param("bcrPos") String bcrPos, @Param("invNo") String invNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<DbSysJobhst> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_SYS_JOBHST
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(DbSysJobhst record);
}