package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.IfWcs02;
import java.util.List;

public interface IfWcs02Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_02
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(String locaky);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_02
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(IfWcs02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_02
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    IfWcs02 selectByPrimaryKey(String locaky);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_02
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<IfWcs02> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_02
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(IfWcs02 record);
}