package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.IfWcs10;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IfWcs10Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_10
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(@Param("invcno") String invcno, @Param("locasr") String locasr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_10
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(IfWcs10 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_10
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    IfWcs10 selectByPrimaryKey(@Param("invcno") String invcno, @Param("locasr") String locasr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_10
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<IfWcs10> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_10
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(IfWcs10 record);
}