package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.IfWcs16;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IfWcs16Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_16
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(@Param("taskky") String taskky, @Param("taskit") String taskit, @Param("crcLoct") String crcLoct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_16
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(IfWcs16 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_16
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    IfWcs16 selectByPrimaryKey(@Param("taskky") String taskky, @Param("taskit") String taskit, @Param("crcLoct") String crcLoct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_16
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<IfWcs16> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_16
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(IfWcs16 record);
}