package com.fnwcs.pda.app.dao;

import com.fnwcs.pda.app.model.IfWcs12;
import java.util.List;

public interface IfWcs12Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_12
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int deleteByPrimaryKey(String invcno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_12
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int insert(IfWcs12 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_12
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    IfWcs12 selectByPrimaryKey(String invcno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_12
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    List<IfWcs12> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_WCS_12
     *
     * @mbg.generated Wed Aug 11 12:35:31 KST 2021
     */
    int updateByPrimaryKey(IfWcs12 record);
}