package com.fnwcs.pda.app.model;

import java.util.Date;

public class DbComCode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.CLASS_CODE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String classCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.COM_CODE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String comCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.COM_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String comName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.USE_YN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String useYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CODE.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bkckFg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.CLASS_CODE
	 * @return  the value of DB_COM_CODE.CLASS_CODE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.CLASS_CODE
	 * @param classCode  the value for DB_COM_CODE.CLASS_CODE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setClassCode(String classCode) {
		this.classCode = classCode == null ? null : classCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.COM_CODE
	 * @return  the value of DB_COM_CODE.COM_CODE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getComCode() {
		return comCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.COM_CODE
	 * @param comCode  the value for DB_COM_CODE.COM_CODE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setComCode(String comCode) {
		this.comCode = comCode == null ? null : comCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.COM_NAME
	 * @return  the value of DB_COM_CODE.COM_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getComName() {
		return comName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.COM_NAME
	 * @param comName  the value for DB_COM_CODE.COM_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setComName(String comName) {
		this.comName = comName == null ? null : comName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.USE_YN
	 * @return  the value of DB_COM_CODE.USE_YN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getUseYn() {
		return useYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.USE_YN
	 * @param useYn  the value for DB_COM_CODE.USE_YN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setUseYn(String useYn) {
		this.useYn = useYn == null ? null : useYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.REMARKS
	 * @return  the value of DB_COM_CODE.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.REMARKS
	 * @param remarks  the value for DB_COM_CODE.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.REG_USER_ID
	 * @return  the value of DB_COM_CODE.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.REG_USER_ID
	 * @param regUserId  the value for DB_COM_CODE.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.REG_DTM
	 * @return  the value of DB_COM_CODE.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.REG_DTM
	 * @param regDtm  the value for DB_COM_CODE.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.MOD_USER_ID
	 * @return  the value of DB_COM_CODE.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.MOD_USER_ID
	 * @param modUserId  the value for DB_COM_CODE.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.MOD_DTM
	 * @return  the value of DB_COM_CODE.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.MOD_DTM
	 * @param modDtm  the value for DB_COM_CODE.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CODE.BKCK_FG
	 * @return  the value of DB_COM_CODE.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBkckFg() {
		return bkckFg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CODE.BKCK_FG
	 * @param bkckFg  the value for DB_COM_CODE.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBkckFg(String bkckFg) {
		this.bkckFg = bkckFg == null ? null : bkckFg.trim();
	}
}