package com.fnwcs.pda.app.model;

import java.util.Date;

public class DbComUsrmst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_USID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uUsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_USNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uUsno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_UANO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uUano;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_EXDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uExdt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_PASS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uPass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_PUDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uPudt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_USYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uUsyn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_LFTF
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uLftf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_LFDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uLfdt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_LFAU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uLfau;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_LFAD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uLfad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_DEPT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uDept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_AUTI
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uAuti;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_SVYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uSvyn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_CFID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uCfid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_CFDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uCfdt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_IPIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uIpip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.U_GRUP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uGrup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bkckFg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_USID
	 * @return  the value of DB_COM_USRMST.U_USID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuUsid() {
		return uUsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_USID
	 * @param uUsid  the value for DB_COM_USRMST.U_USID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuUsid(String uUsid) {
		this.uUsid = uUsid == null ? null : uUsid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_NAME
	 * @return  the value of DB_COM_USRMST.U_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuName() {
		return uName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_NAME
	 * @param uName  the value for DB_COM_USRMST.U_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuName(String uName) {
		this.uName = uName == null ? null : uName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_USNO
	 * @return  the value of DB_COM_USRMST.U_USNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuUsno() {
		return uUsno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_USNO
	 * @param uUsno  the value for DB_COM_USRMST.U_USNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuUsno(String uUsno) {
		this.uUsno = uUsno == null ? null : uUsno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_UANO
	 * @return  the value of DB_COM_USRMST.U_UANO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuUano() {
		return uUano;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_UANO
	 * @param uUano  the value for DB_COM_USRMST.U_UANO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuUano(String uUano) {
		this.uUano = uUano == null ? null : uUano.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_EXDT
	 * @return  the value of DB_COM_USRMST.U_EXDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuExdt() {
		return uExdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_EXDT
	 * @param uExdt  the value for DB_COM_USRMST.U_EXDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuExdt(String uExdt) {
		this.uExdt = uExdt == null ? null : uExdt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_PASS
	 * @return  the value of DB_COM_USRMST.U_PASS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuPass() {
		return uPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_PASS
	 * @param uPass  the value for DB_COM_USRMST.U_PASS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuPass(String uPass) {
		this.uPass = uPass == null ? null : uPass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_PUDT
	 * @return  the value of DB_COM_USRMST.U_PUDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuPudt() {
		return uPudt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_PUDT
	 * @param uPudt  the value for DB_COM_USRMST.U_PUDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuPudt(String uPudt) {
		this.uPudt = uPudt == null ? null : uPudt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_USYN
	 * @return  the value of DB_COM_USRMST.U_USYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuUsyn() {
		return uUsyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_USYN
	 * @param uUsyn  the value for DB_COM_USRMST.U_USYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuUsyn(String uUsyn) {
		this.uUsyn = uUsyn == null ? null : uUsyn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_LFTF
	 * @return  the value of DB_COM_USRMST.U_LFTF
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuLftf() {
		return uLftf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_LFTF
	 * @param uLftf  the value for DB_COM_USRMST.U_LFTF
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuLftf(String uLftf) {
		this.uLftf = uLftf == null ? null : uLftf.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_LFDT
	 * @return  the value of DB_COM_USRMST.U_LFDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuLfdt() {
		return uLfdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_LFDT
	 * @param uLfdt  the value for DB_COM_USRMST.U_LFDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuLfdt(String uLfdt) {
		this.uLfdt = uLfdt == null ? null : uLfdt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_LFAU
	 * @return  the value of DB_COM_USRMST.U_LFAU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuLfau() {
		return uLfau;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_LFAU
	 * @param uLfau  the value for DB_COM_USRMST.U_LFAU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuLfau(String uLfau) {
		this.uLfau = uLfau == null ? null : uLfau.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_LFAD
	 * @return  the value of DB_COM_USRMST.U_LFAD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuLfad() {
		return uLfad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_LFAD
	 * @param uLfad  the value for DB_COM_USRMST.U_LFAD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuLfad(String uLfad) {
		this.uLfad = uLfad == null ? null : uLfad.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_DEPT
	 * @return  the value of DB_COM_USRMST.U_DEPT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuDept() {
		return uDept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_DEPT
	 * @param uDept  the value for DB_COM_USRMST.U_DEPT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuDept(String uDept) {
		this.uDept = uDept == null ? null : uDept.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_AUTI
	 * @return  the value of DB_COM_USRMST.U_AUTI
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuAuti() {
		return uAuti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_AUTI
	 * @param uAuti  the value for DB_COM_USRMST.U_AUTI
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuAuti(String uAuti) {
		this.uAuti = uAuti == null ? null : uAuti.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_SVYN
	 * @return  the value of DB_COM_USRMST.U_SVYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuSvyn() {
		return uSvyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_SVYN
	 * @param uSvyn  the value for DB_COM_USRMST.U_SVYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuSvyn(String uSvyn) {
		this.uSvyn = uSvyn == null ? null : uSvyn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_CFID
	 * @return  the value of DB_COM_USRMST.U_CFID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuCfid() {
		return uCfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_CFID
	 * @param uCfid  the value for DB_COM_USRMST.U_CFID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuCfid(String uCfid) {
		this.uCfid = uCfid == null ? null : uCfid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_CFDT
	 * @return  the value of DB_COM_USRMST.U_CFDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuCfdt() {
		return uCfdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_CFDT
	 * @param uCfdt  the value for DB_COM_USRMST.U_CFDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuCfdt(String uCfdt) {
		this.uCfdt = uCfdt == null ? null : uCfdt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_IPIP
	 * @return  the value of DB_COM_USRMST.U_IPIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuIpip() {
		return uIpip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_IPIP
	 * @param uIpip  the value for DB_COM_USRMST.U_IPIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuIpip(String uIpip) {
		this.uIpip = uIpip == null ? null : uIpip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.U_GRUP
	 * @return  the value of DB_COM_USRMST.U_GRUP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getuGrup() {
		return uGrup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.U_GRUP
	 * @param uGrup  the value for DB_COM_USRMST.U_GRUP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setuGrup(String uGrup) {
		this.uGrup = uGrup == null ? null : uGrup.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.REG_USER_ID
	 * @return  the value of DB_COM_USRMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.REG_USER_ID
	 * @param regUserId  the value for DB_COM_USRMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.REG_DTM
	 * @return  the value of DB_COM_USRMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.REG_DTM
	 * @param regDtm  the value for DB_COM_USRMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.MOD_USER_ID
	 * @return  the value of DB_COM_USRMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.MOD_USER_ID
	 * @param modUserId  the value for DB_COM_USRMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.MOD_DTM
	 * @return  the value of DB_COM_USRMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.MOD_DTM
	 * @param modDtm  the value for DB_COM_USRMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRMST.BKCK_FG
	 * @return  the value of DB_COM_USRMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBkckFg() {
		return bkckFg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRMST.BKCK_FG
	 * @param bkckFg  the value for DB_COM_USRMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBkckFg(String bkckFg) {
		this.bkckFg = bkckFg == null ? null : bkckFg.trim();
	}
}