package com.fnwcs.pda.app.model;

import java.util.Date;

public class DbComMnumst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_MNID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String mMnid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_LEVL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String mLevl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_PMID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String mPmid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String mName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_IPIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String mIpip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_BRFM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String mBrfm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_AUT1
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String mAut1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_CFID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String mCfid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_CFDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date mCfdt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_USYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String mUsyn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.M_INDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date mIndt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_MNUMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bkckFg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_MNID
	 * @return  the value of DB_COM_MNUMST.M_MNID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getmMnid() {
		return mMnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_MNID
	 * @param mMnid  the value for DB_COM_MNUMST.M_MNID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmMnid(String mMnid) {
		this.mMnid = mMnid == null ? null : mMnid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_LEVL
	 * @return  the value of DB_COM_MNUMST.M_LEVL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getmLevl() {
		return mLevl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_LEVL
	 * @param mLevl  the value for DB_COM_MNUMST.M_LEVL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmLevl(String mLevl) {
		this.mLevl = mLevl == null ? null : mLevl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_PMID
	 * @return  the value of DB_COM_MNUMST.M_PMID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getmPmid() {
		return mPmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_PMID
	 * @param mPmid  the value for DB_COM_MNUMST.M_PMID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmPmid(String mPmid) {
		this.mPmid = mPmid == null ? null : mPmid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_NAME
	 * @return  the value of DB_COM_MNUMST.M_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getmName() {
		return mName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_NAME
	 * @param mName  the value for DB_COM_MNUMST.M_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmName(String mName) {
		this.mName = mName == null ? null : mName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_IPIP
	 * @return  the value of DB_COM_MNUMST.M_IPIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getmIpip() {
		return mIpip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_IPIP
	 * @param mIpip  the value for DB_COM_MNUMST.M_IPIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmIpip(String mIpip) {
		this.mIpip = mIpip == null ? null : mIpip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_BRFM
	 * @return  the value of DB_COM_MNUMST.M_BRFM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getmBrfm() {
		return mBrfm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_BRFM
	 * @param mBrfm  the value for DB_COM_MNUMST.M_BRFM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmBrfm(String mBrfm) {
		this.mBrfm = mBrfm == null ? null : mBrfm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_AUT1
	 * @return  the value of DB_COM_MNUMST.M_AUT1
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getmAut1() {
		return mAut1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_AUT1
	 * @param mAut1  the value for DB_COM_MNUMST.M_AUT1
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmAut1(String mAut1) {
		this.mAut1 = mAut1 == null ? null : mAut1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_CFID
	 * @return  the value of DB_COM_MNUMST.M_CFID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getmCfid() {
		return mCfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_CFID
	 * @param mCfid  the value for DB_COM_MNUMST.M_CFID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmCfid(String mCfid) {
		this.mCfid = mCfid == null ? null : mCfid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_CFDT
	 * @return  the value of DB_COM_MNUMST.M_CFDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getmCfdt() {
		return mCfdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_CFDT
	 * @param mCfdt  the value for DB_COM_MNUMST.M_CFDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmCfdt(Date mCfdt) {
		this.mCfdt = mCfdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_USYN
	 * @return  the value of DB_COM_MNUMST.M_USYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getmUsyn() {
		return mUsyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_USYN
	 * @param mUsyn  the value for DB_COM_MNUMST.M_USYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmUsyn(String mUsyn) {
		this.mUsyn = mUsyn == null ? null : mUsyn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.M_INDT
	 * @return  the value of DB_COM_MNUMST.M_INDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getmIndt() {
		return mIndt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.M_INDT
	 * @param mIndt  the value for DB_COM_MNUMST.M_INDT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setmIndt(Date mIndt) {
		this.mIndt = mIndt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.REMARKS
	 * @return  the value of DB_COM_MNUMST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.REMARKS
	 * @param remarks  the value for DB_COM_MNUMST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.REG_USER_ID
	 * @return  the value of DB_COM_MNUMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.REG_USER_ID
	 * @param regUserId  the value for DB_COM_MNUMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.REG_DTM
	 * @return  the value of DB_COM_MNUMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.REG_DTM
	 * @param regDtm  the value for DB_COM_MNUMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.MOD_USER_ID
	 * @return  the value of DB_COM_MNUMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.MOD_USER_ID
	 * @param modUserId  the value for DB_COM_MNUMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.MOD_DTM
	 * @return  the value of DB_COM_MNUMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.MOD_DTM
	 * @param modDtm  the value for DB_COM_MNUMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_MNUMST.BKCK_FG
	 * @return  the value of DB_COM_MNUMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBkckFg() {
		return bkckFg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_MNUMST.BKCK_FG
	 * @param bkckFg  the value for DB_COM_MNUMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBkckFg(String bkckFg) {
		this.bkckFg = bkckFg == null ? null : bkckFg.trim();
	}
}