package com.fnwcs.pda.app.model;

import java.util.Date;

public class DbComCfg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.HOST_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String hostName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.HOST_IP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String hostIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.HOST_PORT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String hostPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.STON_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String stonNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_CFG.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bkckFg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.HOST_NAME
	 * @return  the value of DB_COM_CFG.HOST_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getHostName() {
		return hostName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.HOST_NAME
	 * @param hostName  the value for DB_COM_CFG.HOST_NAME
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setHostName(String hostName) {
		this.hostName = hostName == null ? null : hostName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.HOST_IP
	 * @return  the value of DB_COM_CFG.HOST_IP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getHostIp() {
		return hostIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.HOST_IP
	 * @param hostIp  the value for DB_COM_CFG.HOST_IP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setHostIp(String hostIp) {
		this.hostIp = hostIp == null ? null : hostIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.HOST_PORT
	 * @return  the value of DB_COM_CFG.HOST_PORT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getHostPort() {
		return hostPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.HOST_PORT
	 * @param hostPort  the value for DB_COM_CFG.HOST_PORT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setHostPort(String hostPort) {
		this.hostPort = hostPort == null ? null : hostPort.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.STON_NO
	 * @return  the value of DB_COM_CFG.STON_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getStonNo() {
		return stonNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.STON_NO
	 * @param stonNo  the value for DB_COM_CFG.STON_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setStonNo(String stonNo) {
		this.stonNo = stonNo == null ? null : stonNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.REMARKS
	 * @return  the value of DB_COM_CFG.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.REMARKS
	 * @param remarks  the value for DB_COM_CFG.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.REG_USER_ID
	 * @return  the value of DB_COM_CFG.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.REG_USER_ID
	 * @param regUserId  the value for DB_COM_CFG.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.REG_DTM
	 * @return  the value of DB_COM_CFG.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.REG_DTM
	 * @param regDtm  the value for DB_COM_CFG.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.MOD_USER_ID
	 * @return  the value of DB_COM_CFG.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.MOD_USER_ID
	 * @param modUserId  the value for DB_COM_CFG.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.MOD_DTM
	 * @return  the value of DB_COM_CFG.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.MOD_DTM
	 * @param modDtm  the value for DB_COM_CFG.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_CFG.BKCK_FG
	 * @return  the value of DB_COM_CFG.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBkckFg() {
		return bkckFg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_CFG.BKCK_FG
	 * @param bkckFg  the value for DB_COM_CFG.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBkckFg(String bkckFg) {
		this.bkckFg = bkckFg == null ? null : bkckFg.trim();
	}
}