package com.fnwcs.pda.app.model;

import java.util.Date;

public class DbComEqucom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.EQU_COM_EQUIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String equComEquip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.EQU_COM_EQNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String equComEqno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.EQU_COM_KIND
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String equComKind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.EQU_COM_DATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date equComDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.EQU_COM_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String equComData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_EQUCOM.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bkckFg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.EQU_COM_EQUIP
	 * @return  the value of DB_COM_EQUCOM.EQU_COM_EQUIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getEquComEquip() {
		return equComEquip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.EQU_COM_EQUIP
	 * @param equComEquip  the value for DB_COM_EQUCOM.EQU_COM_EQUIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setEquComEquip(String equComEquip) {
		this.equComEquip = equComEquip == null ? null : equComEquip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.EQU_COM_EQNO
	 * @return  the value of DB_COM_EQUCOM.EQU_COM_EQNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getEquComEqno() {
		return equComEqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.EQU_COM_EQNO
	 * @param equComEqno  the value for DB_COM_EQUCOM.EQU_COM_EQNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setEquComEqno(String equComEqno) {
		this.equComEqno = equComEqno == null ? null : equComEqno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.EQU_COM_KIND
	 * @return  the value of DB_COM_EQUCOM.EQU_COM_KIND
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getEquComKind() {
		return equComKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.EQU_COM_KIND
	 * @param equComKind  the value for DB_COM_EQUCOM.EQU_COM_KIND
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setEquComKind(String equComKind) {
		this.equComKind = equComKind == null ? null : equComKind.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.EQU_COM_DATE
	 * @return  the value of DB_COM_EQUCOM.EQU_COM_DATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getEquComDate() {
		return equComDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.EQU_COM_DATE
	 * @param equComDate  the value for DB_COM_EQUCOM.EQU_COM_DATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setEquComDate(Date equComDate) {
		this.equComDate = equComDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.EQU_COM_DATA
	 * @return  the value of DB_COM_EQUCOM.EQU_COM_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getEquComData() {
		return equComData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.EQU_COM_DATA
	 * @param equComData  the value for DB_COM_EQUCOM.EQU_COM_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setEquComData(String equComData) {
		this.equComData = equComData == null ? null : equComData.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.REG_USER_ID
	 * @return  the value of DB_COM_EQUCOM.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.REG_USER_ID
	 * @param regUserId  the value for DB_COM_EQUCOM.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.REG_DTM
	 * @return  the value of DB_COM_EQUCOM.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.REG_DTM
	 * @param regDtm  the value for DB_COM_EQUCOM.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.MOD_USER_ID
	 * @return  the value of DB_COM_EQUCOM.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.MOD_USER_ID
	 * @param modUserId  the value for DB_COM_EQUCOM.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.MOD_DTM
	 * @return  the value of DB_COM_EQUCOM.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.MOD_DTM
	 * @param modDtm  the value for DB_COM_EQUCOM.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_EQUCOM.BKCK_FG
	 * @return  the value of DB_COM_EQUCOM.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBkckFg() {
		return bkckFg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_EQUCOM.BKCK_FG
	 * @param bkckFg  the value for DB_COM_EQUCOM.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBkckFg(String bkckFg) {
		this.bkckFg = bkckFg == null ? null : bkckFg.trim();
	}
}