package com.fnwcs.pda.app.model;

import java.util.Date;

public class DbComUsraut {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRAUT.UA_USID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uaUsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRAUT.UA_MNID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String uaMnid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRAUT.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRAUT.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRAUT.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRAUT.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRAUT.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_COM_USRAUT.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bkckFg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRAUT.UA_USID
	 * @return  the value of DB_COM_USRAUT.UA_USID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getUaUsid() {
		return uaUsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRAUT.UA_USID
	 * @param uaUsid  the value for DB_COM_USRAUT.UA_USID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setUaUsid(String uaUsid) {
		this.uaUsid = uaUsid == null ? null : uaUsid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRAUT.UA_MNID
	 * @return  the value of DB_COM_USRAUT.UA_MNID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getUaMnid() {
		return uaMnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRAUT.UA_MNID
	 * @param uaMnid  the value for DB_COM_USRAUT.UA_MNID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setUaMnid(String uaMnid) {
		this.uaMnid = uaMnid == null ? null : uaMnid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRAUT.REMARKS
	 * @return  the value of DB_COM_USRAUT.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRAUT.REMARKS
	 * @param remarks  the value for DB_COM_USRAUT.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRAUT.REG_USER_ID
	 * @return  the value of DB_COM_USRAUT.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRAUT.REG_USER_ID
	 * @param regUserId  the value for DB_COM_USRAUT.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRAUT.REG_DTM
	 * @return  the value of DB_COM_USRAUT.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRAUT.REG_DTM
	 * @param regDtm  the value for DB_COM_USRAUT.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRAUT.MOD_USER_ID
	 * @return  the value of DB_COM_USRAUT.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRAUT.MOD_USER_ID
	 * @param modUserId  the value for DB_COM_USRAUT.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRAUT.MOD_DTM
	 * @return  the value of DB_COM_USRAUT.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRAUT.MOD_DTM
	 * @param modDtm  the value for DB_COM_USRAUT.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_COM_USRAUT.BKCK_FG
	 * @return  the value of DB_COM_USRAUT.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBkckFg() {
		return bkckFg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_COM_USRAUT.BKCK_FG
	 * @param bkckFg  the value for DB_COM_USRAUT.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBkckFg(String bkckFg) {
		this.bkckFg = bkckFg == null ? null : bkckFg.trim();
	}
}