package com.fnwcs.pda.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class DbCrcJobmst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String jobNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.SUB_JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String subJobNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.LANK_SEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String lankSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.CMD_DIV
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String cmdDiv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.JOB_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String jobSts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.JOB_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date jobDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String taskky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.TASKIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String taskit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.LOCAFR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locafr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.LOCATO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qttaor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qtcomp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.ERR_CD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String errCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.ERR_MSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String errMsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.BAR_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String barData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.DSP_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String dspData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_CRC_JOBMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bkckFg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.JOB_NO
	 * @return  the value of DB_CRC_JOBMST.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getJobNo() {
		return jobNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.JOB_NO
	 * @param jobNo  the value for DB_CRC_JOBMST.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setJobNo(String jobNo) {
		this.jobNo = jobNo == null ? null : jobNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.SUB_JOB_NO
	 * @return  the value of DB_CRC_JOBMST.SUB_JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSubJobNo() {
		return subJobNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.SUB_JOB_NO
	 * @param subJobNo  the value for DB_CRC_JOBMST.SUB_JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSubJobNo(String subJobNo) {
		this.subJobNo = subJobNo == null ? null : subJobNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.LANK_SEQ
	 * @return  the value of DB_CRC_JOBMST.LANK_SEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLankSeq() {
		return lankSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.LANK_SEQ
	 * @param lankSeq  the value for DB_CRC_JOBMST.LANK_SEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLankSeq(String lankSeq) {
		this.lankSeq = lankSeq == null ? null : lankSeq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.CMD_DIV
	 * @return  the value of DB_CRC_JOBMST.CMD_DIV
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCmdDiv() {
		return cmdDiv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.CMD_DIV
	 * @param cmdDiv  the value for DB_CRC_JOBMST.CMD_DIV
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmdDiv(String cmdDiv) {
		this.cmdDiv = cmdDiv == null ? null : cmdDiv.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.JOB_STS
	 * @return  the value of DB_CRC_JOBMST.JOB_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getJobSts() {
		return jobSts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.JOB_STS
	 * @param jobSts  the value for DB_CRC_JOBMST.JOB_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setJobSts(String jobSts) {
		this.jobSts = jobSts == null ? null : jobSts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.JOB_DTM
	 * @return  the value of DB_CRC_JOBMST.JOB_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getJobDtm() {
		return jobDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.JOB_DTM
	 * @param jobDtm  the value for DB_CRC_JOBMST.JOB_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setJobDtm(Date jobDtm) {
		this.jobDtm = jobDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.TASKKY
	 * @return  the value of DB_CRC_JOBMST.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTaskky() {
		return taskky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.TASKKY
	 * @param taskky  the value for DB_CRC_JOBMST.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTaskky(String taskky) {
		this.taskky = taskky == null ? null : taskky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.TASKIT
	 * @return  the value of DB_CRC_JOBMST.TASKIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTaskit() {
		return taskit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.TASKIT
	 * @param taskit  the value for DB_CRC_JOBMST.TASKIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTaskit(String taskit) {
		this.taskit = taskit == null ? null : taskit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.LOCAFR
	 * @return  the value of DB_CRC_JOBMST.LOCAFR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocafr() {
		return locafr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.LOCAFR
	 * @param locafr  the value for DB_CRC_JOBMST.LOCAFR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocafr(String locafr) {
		this.locafr = locafr == null ? null : locafr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.LOCATO
	 * @return  the value of DB_CRC_JOBMST.LOCATO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocato() {
		return locato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.LOCATO
	 * @param locato  the value for DB_CRC_JOBMST.LOCATO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocato(String locato) {
		this.locato = locato == null ? null : locato.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.QTTAOR
	 * @return  the value of DB_CRC_JOBMST.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQttaor() {
		return qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.QTTAOR
	 * @param qttaor  the value for DB_CRC_JOBMST.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQttaor(BigDecimal qttaor) {
		this.qttaor = qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.QTCOMP
	 * @return  the value of DB_CRC_JOBMST.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQtcomp() {
		return qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.QTCOMP
	 * @param qtcomp  the value for DB_CRC_JOBMST.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQtcomp(BigDecimal qtcomp) {
		this.qtcomp = qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.ERR_CD
	 * @return  the value of DB_CRC_JOBMST.ERR_CD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getErrCd() {
		return errCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.ERR_CD
	 * @param errCd  the value for DB_CRC_JOBMST.ERR_CD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setErrCd(String errCd) {
		this.errCd = errCd == null ? null : errCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.ERR_MSG
	 * @return  the value of DB_CRC_JOBMST.ERR_MSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getErrMsg() {
		return errMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.ERR_MSG
	 * @param errMsg  the value for DB_CRC_JOBMST.ERR_MSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg == null ? null : errMsg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.BAR_DATA
	 * @return  the value of DB_CRC_JOBMST.BAR_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBarData() {
		return barData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.BAR_DATA
	 * @param barData  the value for DB_CRC_JOBMST.BAR_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBarData(String barData) {
		this.barData = barData == null ? null : barData.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.DSP_DATA
	 * @return  the value of DB_CRC_JOBMST.DSP_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDspData() {
		return dspData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.DSP_DATA
	 * @param dspData  the value for DB_CRC_JOBMST.DSP_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDspData(String dspData) {
		this.dspData = dspData == null ? null : dspData.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.REMARKS
	 * @return  the value of DB_CRC_JOBMST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.REMARKS
	 * @param remarks  the value for DB_CRC_JOBMST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.REG_USER_ID
	 * @return  the value of DB_CRC_JOBMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.REG_USER_ID
	 * @param regUserId  the value for DB_CRC_JOBMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.REG_DTM
	 * @return  the value of DB_CRC_JOBMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.REG_DTM
	 * @param regDtm  the value for DB_CRC_JOBMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.MOD_USER_ID
	 * @return  the value of DB_CRC_JOBMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.MOD_USER_ID
	 * @param modUserId  the value for DB_CRC_JOBMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.MOD_DTM
	 * @return  the value of DB_CRC_JOBMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.MOD_DTM
	 * @param modDtm  the value for DB_CRC_JOBMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_CRC_JOBMST.BKCK_FG
	 * @return  the value of DB_CRC_JOBMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBkckFg() {
		return bkckFg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_CRC_JOBMST.BKCK_FG
	 * @param bkckFg  the value for DB_CRC_JOBMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBkckFg(String bkckFg) {
		this.bkckFg = bkckFg == null ? null : bkckFg.trim();
	}
}