package com.fnwcs.pda.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class DbStoStodtl {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.WHID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String whid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String loct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ownrky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.LOCAKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locaky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String skukey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String desc01;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.DESC02
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String desc02;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.STOQTY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal stoqty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.STOCK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String stockSts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STODTL.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.WHID
	 * @return  the value of DB_STO_STODTL.WHID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getWhid() {
		return whid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.WHID
	 * @param whid  the value for DB_STO_STODTL.WHID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setWhid(String whid) {
		this.whid = whid == null ? null : whid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.LOCT
	 * @return  the value of DB_STO_STODTL.LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLoct() {
		return loct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.LOCT
	 * @param loct  the value for DB_STO_STODTL.LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLoct(String loct) {
		this.loct = loct == null ? null : loct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.OWNRKY
	 * @return  the value of DB_STO_STODTL.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getOwnrky() {
		return ownrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.OWNRKY
	 * @param ownrky  the value for DB_STO_STODTL.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setOwnrky(String ownrky) {
		this.ownrky = ownrky == null ? null : ownrky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.LOCAKY
	 * @return  the value of DB_STO_STODTL.LOCAKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocaky() {
		return locaky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.LOCAKY
	 * @param locaky  the value for DB_STO_STODTL.LOCAKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocaky(String locaky) {
		this.locaky = locaky == null ? null : locaky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.SKUKEY
	 * @return  the value of DB_STO_STODTL.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSkukey() {
		return skukey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.SKUKEY
	 * @param skukey  the value for DB_STO_STODTL.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSkukey(String skukey) {
		this.skukey = skukey == null ? null : skukey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.DESC01
	 * @return  the value of DB_STO_STODTL.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDesc01() {
		return desc01;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.DESC01
	 * @param desc01  the value for DB_STO_STODTL.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDesc01(String desc01) {
		this.desc01 = desc01 == null ? null : desc01.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.DESC02
	 * @return  the value of DB_STO_STODTL.DESC02
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDesc02() {
		return desc02;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.DESC02
	 * @param desc02  the value for DB_STO_STODTL.DESC02
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDesc02(String desc02) {
		this.desc02 = desc02 == null ? null : desc02.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.STOQTY
	 * @return  the value of DB_STO_STODTL.STOQTY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getStoqty() {
		return stoqty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.STOQTY
	 * @param stoqty  the value for DB_STO_STODTL.STOQTY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setStoqty(BigDecimal stoqty) {
		this.stoqty = stoqty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.WEIGHT
	 * @return  the value of DB_STO_STODTL.WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.WEIGHT
	 * @param weight  the value for DB_STO_STODTL.WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.STOCK_STS
	 * @return  the value of DB_STO_STODTL.STOCK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getStockSts() {
		return stockSts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.STOCK_STS
	 * @param stockSts  the value for DB_STO_STODTL.STOCK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setStockSts(String stockSts) {
		this.stockSts = stockSts == null ? null : stockSts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.REG_USER_ID
	 * @return  the value of DB_STO_STODTL.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.REG_USER_ID
	 * @param regUserId  the value for DB_STO_STODTL.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.REG_DTM
	 * @return  the value of DB_STO_STODTL.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.REG_DTM
	 * @param regDtm  the value for DB_STO_STODTL.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.MOD_USER_ID
	 * @return  the value of DB_STO_STODTL.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.MOD_USER_ID
	 * @param modUserId  the value for DB_STO_STODTL.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STODTL.MOD_DTM
	 * @return  the value of DB_STO_STODTL.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STODTL.MOD_DTM
	 * @param modDtm  the value for DB_STO_STODTL.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}
}