package com.fnwcs.pda.app.model;

import java.util.Date;

public class DbStoStomst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.WHID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String whid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String loct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.ROW
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String row;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.BAY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.LEV
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String lev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.RACK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String rackSts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.STOCK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String stockSts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.PLT_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String pltId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_STO_STOMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bkckFg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.WHID
	 * @return  the value of DB_STO_STOMST.WHID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getWhid() {
		return whid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.WHID
	 * @param whid  the value for DB_STO_STOMST.WHID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setWhid(String whid) {
		this.whid = whid == null ? null : whid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.LOCT
	 * @return  the value of DB_STO_STOMST.LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLoct() {
		return loct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.LOCT
	 * @param loct  the value for DB_STO_STOMST.LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLoct(String loct) {
		this.loct = loct == null ? null : loct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.ROW
	 * @return  the value of DB_STO_STOMST.ROW
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRow() {
		return row;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.ROW
	 * @param row  the value for DB_STO_STOMST.ROW
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRow(String row) {
		this.row = row == null ? null : row.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.BAY
	 * @return  the value of DB_STO_STOMST.BAY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBay() {
		return bay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.BAY
	 * @param bay  the value for DB_STO_STOMST.BAY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBay(String bay) {
		this.bay = bay == null ? null : bay.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.LEV
	 * @return  the value of DB_STO_STOMST.LEV
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLev() {
		return lev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.LEV
	 * @param lev  the value for DB_STO_STOMST.LEV
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLev(String lev) {
		this.lev = lev == null ? null : lev.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.RACK_STS
	 * @return  the value of DB_STO_STOMST.RACK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRackSts() {
		return rackSts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.RACK_STS
	 * @param rackSts  the value for DB_STO_STOMST.RACK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRackSts(String rackSts) {
		this.rackSts = rackSts == null ? null : rackSts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.STOCK_STS
	 * @return  the value of DB_STO_STOMST.STOCK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getStockSts() {
		return stockSts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.STOCK_STS
	 * @param stockSts  the value for DB_STO_STOMST.STOCK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setStockSts(String stockSts) {
		this.stockSts = stockSts == null ? null : stockSts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.PLT_ID
	 * @return  the value of DB_STO_STOMST.PLT_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getPltId() {
		return pltId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.PLT_ID
	 * @param pltId  the value for DB_STO_STOMST.PLT_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setPltId(String pltId) {
		this.pltId = pltId == null ? null : pltId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.REMARKS
	 * @return  the value of DB_STO_STOMST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.REMARKS
	 * @param remarks  the value for DB_STO_STOMST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.REG_USER_ID
	 * @return  the value of DB_STO_STOMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.REG_USER_ID
	 * @param regUserId  the value for DB_STO_STOMST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.REG_DTM
	 * @return  the value of DB_STO_STOMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.REG_DTM
	 * @param regDtm  the value for DB_STO_STOMST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.MOD_USER_ID
	 * @return  the value of DB_STO_STOMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.MOD_USER_ID
	 * @param modUserId  the value for DB_STO_STOMST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.MOD_DTM
	 * @return  the value of DB_STO_STOMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.MOD_DTM
	 * @param modDtm  the value for DB_STO_STOMST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_STO_STOMST.BKCK_FG
	 * @return  the value of DB_STO_STOMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBkckFg() {
		return bkckFg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_STO_STOMST.BKCK_FG
	 * @param bkckFg  the value for DB_STO_STOMST.BKCK_FG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBkckFg(String bkckFg) {
		this.bkckFg = bkckFg == null ? null : bkckFg.trim();
	}
}