package com.fnwcs.pda.app.model;

import java.util.Date;

public class DbSysErrlog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.LOG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date logDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.LOG_SEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Long logSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.ERR_EQUIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String errEquip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.ERR_EQ_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String errEqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.ERR_CODE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String errCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.ERR_MSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String errMsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.ERR_POS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String errPos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.ERR_STON
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String errSton;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String jobNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String loct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.PLT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String plt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.PLT_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String pltId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_ERRLOG.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.LOG_DTM
	 * @return  the value of DB_SYS_ERRLOG.LOG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getLogDtm() {
		return logDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.LOG_DTM
	 * @param logDtm  the value for DB_SYS_ERRLOG.LOG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLogDtm(Date logDtm) {
		this.logDtm = logDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.LOG_SEQ
	 * @return  the value of DB_SYS_ERRLOG.LOG_SEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Long getLogSeq() {
		return logSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.LOG_SEQ
	 * @param logSeq  the value for DB_SYS_ERRLOG.LOG_SEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLogSeq(Long logSeq) {
		this.logSeq = logSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.ERR_EQUIP
	 * @return  the value of DB_SYS_ERRLOG.ERR_EQUIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getErrEquip() {
		return errEquip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.ERR_EQUIP
	 * @param errEquip  the value for DB_SYS_ERRLOG.ERR_EQUIP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setErrEquip(String errEquip) {
		this.errEquip = errEquip == null ? null : errEquip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.ERR_EQ_NO
	 * @return  the value of DB_SYS_ERRLOG.ERR_EQ_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getErrEqNo() {
		return errEqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.ERR_EQ_NO
	 * @param errEqNo  the value for DB_SYS_ERRLOG.ERR_EQ_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setErrEqNo(String errEqNo) {
		this.errEqNo = errEqNo == null ? null : errEqNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.ERR_CODE
	 * @return  the value of DB_SYS_ERRLOG.ERR_CODE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getErrCode() {
		return errCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.ERR_CODE
	 * @param errCode  the value for DB_SYS_ERRLOG.ERR_CODE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setErrCode(String errCode) {
		this.errCode = errCode == null ? null : errCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.ERR_MSG
	 * @return  the value of DB_SYS_ERRLOG.ERR_MSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getErrMsg() {
		return errMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.ERR_MSG
	 * @param errMsg  the value for DB_SYS_ERRLOG.ERR_MSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg == null ? null : errMsg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.ERR_POS
	 * @return  the value of DB_SYS_ERRLOG.ERR_POS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getErrPos() {
		return errPos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.ERR_POS
	 * @param errPos  the value for DB_SYS_ERRLOG.ERR_POS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setErrPos(String errPos) {
		this.errPos = errPos == null ? null : errPos.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.ERR_STON
	 * @return  the value of DB_SYS_ERRLOG.ERR_STON
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getErrSton() {
		return errSton;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.ERR_STON
	 * @param errSton  the value for DB_SYS_ERRLOG.ERR_STON
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setErrSton(String errSton) {
		this.errSton = errSton == null ? null : errSton.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.JOB_NO
	 * @return  the value of DB_SYS_ERRLOG.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getJobNo() {
		return jobNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.JOB_NO
	 * @param jobNo  the value for DB_SYS_ERRLOG.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setJobNo(String jobNo) {
		this.jobNo = jobNo == null ? null : jobNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.LOCT
	 * @return  the value of DB_SYS_ERRLOG.LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLoct() {
		return loct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.LOCT
	 * @param loct  the value for DB_SYS_ERRLOG.LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLoct(String loct) {
		this.loct = loct == null ? null : loct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.PLT
	 * @return  the value of DB_SYS_ERRLOG.PLT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getPlt() {
		return plt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.PLT
	 * @param plt  the value for DB_SYS_ERRLOG.PLT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setPlt(String plt) {
		this.plt = plt == null ? null : plt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.PLT_ID
	 * @return  the value of DB_SYS_ERRLOG.PLT_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getPltId() {
		return pltId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.PLT_ID
	 * @param pltId  the value for DB_SYS_ERRLOG.PLT_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setPltId(String pltId) {
		this.pltId = pltId == null ? null : pltId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.REMARKS
	 * @return  the value of DB_SYS_ERRLOG.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.REMARKS
	 * @param remarks  the value for DB_SYS_ERRLOG.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_ERRLOG.REG_USER_ID
	 * @return  the value of DB_SYS_ERRLOG.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_ERRLOG.REG_USER_ID
	 * @param regUserId  the value for DB_SYS_ERRLOG.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}
}