package com.fnwcs.pda.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class DbSysClchst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.HST_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date hstDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String taskky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String skukey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ownrky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String desc01;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.LOCASR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locasr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.LOCATG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locatg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qttaor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qtcomp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_CLCHST.CMD_DIV
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String cmdDiv;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.HST_DTM
	 * @return  the value of DB_SYS_CLCHST.HST_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getHstDtm() {
		return hstDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.HST_DTM
	 * @param hstDtm  the value for DB_SYS_CLCHST.HST_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setHstDtm(Date hstDtm) {
		this.hstDtm = hstDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.TASKKY
	 * @return  the value of DB_SYS_CLCHST.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTaskky() {
		return taskky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.TASKKY
	 * @param taskky  the value for DB_SYS_CLCHST.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTaskky(String taskky) {
		this.taskky = taskky == null ? null : taskky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.SKUKEY
	 * @return  the value of DB_SYS_CLCHST.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSkukey() {
		return skukey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.SKUKEY
	 * @param skukey  the value for DB_SYS_CLCHST.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSkukey(String skukey) {
		this.skukey = skukey == null ? null : skukey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.OWNRKY
	 * @return  the value of DB_SYS_CLCHST.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getOwnrky() {
		return ownrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.OWNRKY
	 * @param ownrky  the value for DB_SYS_CLCHST.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setOwnrky(String ownrky) {
		this.ownrky = ownrky == null ? null : ownrky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.DESC01
	 * @return  the value of DB_SYS_CLCHST.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDesc01() {
		return desc01;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.DESC01
	 * @param desc01  the value for DB_SYS_CLCHST.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDesc01(String desc01) {
		this.desc01 = desc01 == null ? null : desc01.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.LOCASR
	 * @return  the value of DB_SYS_CLCHST.LOCASR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocasr() {
		return locasr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.LOCASR
	 * @param locasr  the value for DB_SYS_CLCHST.LOCASR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocasr(String locasr) {
		this.locasr = locasr == null ? null : locasr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.LOCATG
	 * @return  the value of DB_SYS_CLCHST.LOCATG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocatg() {
		return locatg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.LOCATG
	 * @param locatg  the value for DB_SYS_CLCHST.LOCATG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocatg(String locatg) {
		this.locatg = locatg == null ? null : locatg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.QTTAOR
	 * @return  the value of DB_SYS_CLCHST.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQttaor() {
		return qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.QTTAOR
	 * @param qttaor  the value for DB_SYS_CLCHST.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQttaor(BigDecimal qttaor) {
		this.qttaor = qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.QTCOMP
	 * @return  the value of DB_SYS_CLCHST.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQtcomp() {
		return qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.QTCOMP
	 * @param qtcomp  the value for DB_SYS_CLCHST.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQtcomp(BigDecimal qtcomp) {
		this.qtcomp = qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_CLCHST.CMD_DIV
	 * @return  the value of DB_SYS_CLCHST.CMD_DIV
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCmdDiv() {
		return cmdDiv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_CLCHST.CMD_DIV
	 * @param cmdDiv  the value for DB_SYS_CLCHST.CMD_DIV
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmdDiv(String cmdDiv) {
		this.cmdDiv = cmdDiv == null ? null : cmdDiv.trim();
	}
}