package com.fnwcs.pda.app.model;

import java.util.Date;

public class DbSysJobhst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.HST_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date hstDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.BCR_POS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bcrPos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.INV_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String invNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.BCR_MOVE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bcrMove;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.BAR_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String barData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.PID_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String pidNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String jobNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String regUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date regDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DB_SYS_JOBHST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modDtm;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.HST_DTM
	 * @return  the value of DB_SYS_JOBHST.HST_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getHstDtm() {
		return hstDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.HST_DTM
	 * @param hstDtm  the value for DB_SYS_JOBHST.HST_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setHstDtm(Date hstDtm) {
		this.hstDtm = hstDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.BCR_POS
	 * @return  the value of DB_SYS_JOBHST.BCR_POS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBcrPos() {
		return bcrPos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.BCR_POS
	 * @param bcrPos  the value for DB_SYS_JOBHST.BCR_POS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBcrPos(String bcrPos) {
		this.bcrPos = bcrPos == null ? null : bcrPos.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.INV_NO
	 * @return  the value of DB_SYS_JOBHST.INV_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getInvNo() {
		return invNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.INV_NO
	 * @param invNo  the value for DB_SYS_JOBHST.INV_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setInvNo(String invNo) {
		this.invNo = invNo == null ? null : invNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.BCR_MOVE
	 * @return  the value of DB_SYS_JOBHST.BCR_MOVE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBcrMove() {
		return bcrMove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.BCR_MOVE
	 * @param bcrMove  the value for DB_SYS_JOBHST.BCR_MOVE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBcrMove(String bcrMove) {
		this.bcrMove = bcrMove == null ? null : bcrMove.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.BAR_DATA
	 * @return  the value of DB_SYS_JOBHST.BAR_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBarData() {
		return barData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.BAR_DATA
	 * @param barData  the value for DB_SYS_JOBHST.BAR_DATA
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBarData(String barData) {
		this.barData = barData == null ? null : barData.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.PID_NO
	 * @return  the value of DB_SYS_JOBHST.PID_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getPidNo() {
		return pidNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.PID_NO
	 * @param pidNo  the value for DB_SYS_JOBHST.PID_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setPidNo(String pidNo) {
		this.pidNo = pidNo == null ? null : pidNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.JOB_NO
	 * @return  the value of DB_SYS_JOBHST.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getJobNo() {
		return jobNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.JOB_NO
	 * @param jobNo  the value for DB_SYS_JOBHST.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setJobNo(String jobNo) {
		this.jobNo = jobNo == null ? null : jobNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.REMARKS
	 * @return  the value of DB_SYS_JOBHST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.REMARKS
	 * @param remarks  the value for DB_SYS_JOBHST.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.REG_USER_ID
	 * @return  the value of DB_SYS_JOBHST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRegUserId() {
		return regUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.REG_USER_ID
	 * @param regUserId  the value for DB_SYS_JOBHST.REG_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId == null ? null : regUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.REG_DTM
	 * @return  the value of DB_SYS_JOBHST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getRegDtm() {
		return regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.REG_DTM
	 * @param regDtm  the value for DB_SYS_JOBHST.REG_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRegDtm(Date regDtm) {
		this.regDtm = regDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.MOD_USER_ID
	 * @return  the value of DB_SYS_JOBHST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModUserId() {
		return modUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.MOD_USER_ID
	 * @param modUserId  the value for DB_SYS_JOBHST.MOD_USER_ID
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModUserId(String modUserId) {
		this.modUserId = modUserId == null ? null : modUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DB_SYS_JOBHST.MOD_DTM
	 * @return  the value of DB_SYS_JOBHST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModDtm() {
		return modDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DB_SYS_JOBHST.MOD_DTM
	 * @param modDtm  the value for DB_SYS_JOBHST.MOD_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModDtm(Date modDtm) {
		this.modDtm = modDtm;
	}
}