package com.fnwcs.pda.app.model;

import java.util.Date;

public class IfWcs14 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_14.LOCAKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locaky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_14.CRSMOD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String crsmod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_14.CRSSTS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String crssts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_14.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date credate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_14.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String creusr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_14.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String cmpflg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_14.CMPDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date cmpdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_14.CMPMSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String cmpmsg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_14.LOCAKY
	 * @return  the value of IF_WCS_14.LOCAKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocaky() {
		return locaky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_14.LOCAKY
	 * @param locaky  the value for IF_WCS_14.LOCAKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocaky(String locaky) {
		this.locaky = locaky == null ? null : locaky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_14.CRSMOD
	 * @return  the value of IF_WCS_14.CRSMOD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCrsmod() {
		return crsmod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_14.CRSMOD
	 * @param crsmod  the value for IF_WCS_14.CRSMOD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCrsmod(String crsmod) {
		this.crsmod = crsmod == null ? null : crsmod.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_14.CRSSTS
	 * @return  the value of IF_WCS_14.CRSSTS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCrssts() {
		return crssts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_14.CRSSTS
	 * @param crssts  the value for IF_WCS_14.CRSSTS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCrssts(String crssts) {
		this.crssts = crssts == null ? null : crssts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_14.CREDATE
	 * @return  the value of IF_WCS_14.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCredate() {
		return credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_14.CREDATE
	 * @param credate  the value for IF_WCS_14.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCredate(Date credate) {
		this.credate = credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_14.CREUSR
	 * @return  the value of IF_WCS_14.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCreusr() {
		return creusr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_14.CREUSR
	 * @param creusr  the value for IF_WCS_14.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCreusr(String creusr) {
		this.creusr = creusr == null ? null : creusr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_14.CMPFLG
	 * @return  the value of IF_WCS_14.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCmpflg() {
		return cmpflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_14.CMPFLG
	 * @param cmpflg  the value for IF_WCS_14.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpflg(String cmpflg) {
		this.cmpflg = cmpflg == null ? null : cmpflg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_14.CMPDATE
	 * @return  the value of IF_WCS_14.CMPDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCmpdate() {
		return cmpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_14.CMPDATE
	 * @param cmpdate  the value for IF_WCS_14.CMPDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpdate(Date cmpdate) {
		this.cmpdate = cmpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_14.CMPMSG
	 * @return  the value of IF_WCS_14.CMPMSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCmpmsg() {
		return cmpmsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_14.CMPMSG
	 * @param cmpmsg  the value for IF_WCS_14.CMPMSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpmsg(String cmpmsg) {
		this.cmpmsg = cmpmsg == null ? null : cmpmsg.trim();
	}
}