package com.fnwcs.pda.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class IfWcs02 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.LOCAKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locaky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.STATUS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.EQUPTY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String equpty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.LENGTH
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal length;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.WIDTHW
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal widthw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.HEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal height;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date credate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String creusr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_02.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.LOCAKY
	 * @return  the value of IF_WCS_02.LOCAKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocaky() {
		return locaky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.LOCAKY
	 * @param locaky  the value for IF_WCS_02.LOCAKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocaky(String locaky) {
		this.locaky = locaky == null ? null : locaky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.STATUS
	 * @return  the value of IF_WCS_02.STATUS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.STATUS
	 * @param status  the value for IF_WCS_02.STATUS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.EQUPTY
	 * @return  the value of IF_WCS_02.EQUPTY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getEqupty() {
		return equpty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.EQUPTY
	 * @param equpty  the value for IF_WCS_02.EQUPTY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setEqupty(String equpty) {
		this.equpty = equpty == null ? null : equpty.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.LENGTH
	 * @return  the value of IF_WCS_02.LENGTH
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getLength() {
		return length;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.LENGTH
	 * @param length  the value for IF_WCS_02.LENGTH
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLength(BigDecimal length) {
		this.length = length;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.WIDTHW
	 * @return  the value of IF_WCS_02.WIDTHW
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getWidthw() {
		return widthw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.WIDTHW
	 * @param widthw  the value for IF_WCS_02.WIDTHW
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setWidthw(BigDecimal widthw) {
		this.widthw = widthw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.HEIGHT
	 * @return  the value of IF_WCS_02.HEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.HEIGHT
	 * @param height  the value for IF_WCS_02.HEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.WEIGHT
	 * @return  the value of IF_WCS_02.WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.WEIGHT
	 * @param weight  the value for IF_WCS_02.WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.CREDATE
	 * @return  the value of IF_WCS_02.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCredate() {
		return credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.CREDATE
	 * @param credate  the value for IF_WCS_02.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCredate(Date credate) {
		this.credate = credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.CREUSR
	 * @return  the value of IF_WCS_02.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCreusr() {
		return creusr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.CREUSR
	 * @param creusr  the value for IF_WCS_02.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCreusr(String creusr) {
		this.creusr = creusr == null ? null : creusr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_02.REMARKS
	 * @return  the value of IF_WCS_02.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_02.REMARKS
	 * @param remarks  the value for IF_WCS_02.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}
}