package com.fnwcs.pda.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class IfWcs10 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.INVCNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String invcno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.LOCASR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locasr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SHPDAT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String shpdat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.STKNUM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String stknum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.STKSEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Short stkseq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.TMLCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String tmlcd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.TMLNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String tmlnm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.CITYGUNGU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String citygungu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.DONG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String dong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.FILTCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String filtcd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.BRNSHPNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String brnshpnm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.ORDNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ordno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.INVNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String invno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SNPERNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String snpernm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SNPERTEL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String snpertel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SNPERCPNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String snpercpno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SNPERZIPCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String snperzipcd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SNPERADR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String snperadr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SNPERADRDETAIL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String snperadrdetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.ACPERNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String acpernm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.ACPERTEL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String acpertel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.ACPERCPNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String acpercpno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.ACPERZIPCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String acperzipcd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.ACPERADR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String acperadr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.ACPERADRDETAIL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String acperadrdetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.GDSNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String gdsnm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.DLVMSGCONT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String dlvmsgcont;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.FARESCTCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String faresctcd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.DLVFARE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal dlvfare;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.TOTCNT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal totcnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.CCPNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ccpnm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.CCPTEL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ccptel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.DLCNT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String dlcnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.USTRTGSCTCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ustrtgsctcd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.ORDSCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ordsct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SHPOKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String shpoky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SHPOIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String shpoit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ownrky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String skukey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.CTNTYP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ctntyp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qttaor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qtcomp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.QTTRS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qttrs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date credate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String creusr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.TRSFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String trsflg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.TRSDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date trsdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String jobNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.WK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String wkSts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.BCR_POS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String bcrPos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.SKU_WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal skuWeight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.LABEL_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String labelSts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.TEST_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String testSts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.QTY_MODIFY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String qtyModify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.TEST_DATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date testDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.TEST_USER
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String testUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.CHNTYP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String chntyp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.CHNCTN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String chnctn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.MODIFY_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date modifyDtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.MODIFY_USER
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String modifyUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_10.INVNO_CNT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Short invnoCnt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.INVCNO
	 * @return  the value of IF_WCS_10.INVCNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getInvcno() {
		return invcno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.INVCNO
	 * @param invcno  the value for IF_WCS_10.INVCNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setInvcno(String invcno) {
		this.invcno = invcno == null ? null : invcno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.LOCASR
	 * @return  the value of IF_WCS_10.LOCASR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocasr() {
		return locasr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.LOCASR
	 * @param locasr  the value for IF_WCS_10.LOCASR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocasr(String locasr) {
		this.locasr = locasr == null ? null : locasr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SHPDAT
	 * @return  the value of IF_WCS_10.SHPDAT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getShpdat() {
		return shpdat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SHPDAT
	 * @param shpdat  the value for IF_WCS_10.SHPDAT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setShpdat(String shpdat) {
		this.shpdat = shpdat == null ? null : shpdat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.STKNUM
	 * @return  the value of IF_WCS_10.STKNUM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getStknum() {
		return stknum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.STKNUM
	 * @param stknum  the value for IF_WCS_10.STKNUM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setStknum(String stknum) {
		this.stknum = stknum == null ? null : stknum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.STKSEQ
	 * @return  the value of IF_WCS_10.STKSEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Short getStkseq() {
		return stkseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.STKSEQ
	 * @param stkseq  the value for IF_WCS_10.STKSEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setStkseq(Short stkseq) {
		this.stkseq = stkseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.TMLCD
	 * @return  the value of IF_WCS_10.TMLCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTmlcd() {
		return tmlcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.TMLCD
	 * @param tmlcd  the value for IF_WCS_10.TMLCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTmlcd(String tmlcd) {
		this.tmlcd = tmlcd == null ? null : tmlcd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.TMLNM
	 * @return  the value of IF_WCS_10.TMLNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTmlnm() {
		return tmlnm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.TMLNM
	 * @param tmlnm  the value for IF_WCS_10.TMLNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTmlnm(String tmlnm) {
		this.tmlnm = tmlnm == null ? null : tmlnm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.CITYGUNGU
	 * @return  the value of IF_WCS_10.CITYGUNGU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCitygungu() {
		return citygungu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.CITYGUNGU
	 * @param citygungu  the value for IF_WCS_10.CITYGUNGU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCitygungu(String citygungu) {
		this.citygungu = citygungu == null ? null : citygungu.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.DONG
	 * @return  the value of IF_WCS_10.DONG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDong() {
		return dong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.DONG
	 * @param dong  the value for IF_WCS_10.DONG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDong(String dong) {
		this.dong = dong == null ? null : dong.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.FILTCD
	 * @return  the value of IF_WCS_10.FILTCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getFiltcd() {
		return filtcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.FILTCD
	 * @param filtcd  the value for IF_WCS_10.FILTCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setFiltcd(String filtcd) {
		this.filtcd = filtcd == null ? null : filtcd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.BRNSHPNM
	 * @return  the value of IF_WCS_10.BRNSHPNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBrnshpnm() {
		return brnshpnm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.BRNSHPNM
	 * @param brnshpnm  the value for IF_WCS_10.BRNSHPNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBrnshpnm(String brnshpnm) {
		this.brnshpnm = brnshpnm == null ? null : brnshpnm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.ORDNO
	 * @return  the value of IF_WCS_10.ORDNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getOrdno() {
		return ordno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.ORDNO
	 * @param ordno  the value for IF_WCS_10.ORDNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setOrdno(String ordno) {
		this.ordno = ordno == null ? null : ordno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.INVNO
	 * @return  the value of IF_WCS_10.INVNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getInvno() {
		return invno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.INVNO
	 * @param invno  the value for IF_WCS_10.INVNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setInvno(String invno) {
		this.invno = invno == null ? null : invno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SNPERNM
	 * @return  the value of IF_WCS_10.SNPERNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSnpernm() {
		return snpernm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SNPERNM
	 * @param snpernm  the value for IF_WCS_10.SNPERNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSnpernm(String snpernm) {
		this.snpernm = snpernm == null ? null : snpernm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SNPERTEL
	 * @return  the value of IF_WCS_10.SNPERTEL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSnpertel() {
		return snpertel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SNPERTEL
	 * @param snpertel  the value for IF_WCS_10.SNPERTEL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSnpertel(String snpertel) {
		this.snpertel = snpertel == null ? null : snpertel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SNPERCPNO
	 * @return  the value of IF_WCS_10.SNPERCPNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSnpercpno() {
		return snpercpno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SNPERCPNO
	 * @param snpercpno  the value for IF_WCS_10.SNPERCPNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSnpercpno(String snpercpno) {
		this.snpercpno = snpercpno == null ? null : snpercpno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SNPERZIPCD
	 * @return  the value of IF_WCS_10.SNPERZIPCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSnperzipcd() {
		return snperzipcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SNPERZIPCD
	 * @param snperzipcd  the value for IF_WCS_10.SNPERZIPCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSnperzipcd(String snperzipcd) {
		this.snperzipcd = snperzipcd == null ? null : snperzipcd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SNPERADR
	 * @return  the value of IF_WCS_10.SNPERADR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSnperadr() {
		return snperadr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SNPERADR
	 * @param snperadr  the value for IF_WCS_10.SNPERADR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSnperadr(String snperadr) {
		this.snperadr = snperadr == null ? null : snperadr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SNPERADRDETAIL
	 * @return  the value of IF_WCS_10.SNPERADRDETAIL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSnperadrdetail() {
		return snperadrdetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SNPERADRDETAIL
	 * @param snperadrdetail  the value for IF_WCS_10.SNPERADRDETAIL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSnperadrdetail(String snperadrdetail) {
		this.snperadrdetail = snperadrdetail == null ? null : snperadrdetail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.ACPERNM
	 * @return  the value of IF_WCS_10.ACPERNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getAcpernm() {
		return acpernm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.ACPERNM
	 * @param acpernm  the value for IF_WCS_10.ACPERNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setAcpernm(String acpernm) {
		this.acpernm = acpernm == null ? null : acpernm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.ACPERTEL
	 * @return  the value of IF_WCS_10.ACPERTEL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getAcpertel() {
		return acpertel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.ACPERTEL
	 * @param acpertel  the value for IF_WCS_10.ACPERTEL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setAcpertel(String acpertel) {
		this.acpertel = acpertel == null ? null : acpertel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.ACPERCPNO
	 * @return  the value of IF_WCS_10.ACPERCPNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getAcpercpno() {
		return acpercpno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.ACPERCPNO
	 * @param acpercpno  the value for IF_WCS_10.ACPERCPNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setAcpercpno(String acpercpno) {
		this.acpercpno = acpercpno == null ? null : acpercpno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.ACPERZIPCD
	 * @return  the value of IF_WCS_10.ACPERZIPCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getAcperzipcd() {
		return acperzipcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.ACPERZIPCD
	 * @param acperzipcd  the value for IF_WCS_10.ACPERZIPCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setAcperzipcd(String acperzipcd) {
		this.acperzipcd = acperzipcd == null ? null : acperzipcd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.ACPERADR
	 * @return  the value of IF_WCS_10.ACPERADR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getAcperadr() {
		return acperadr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.ACPERADR
	 * @param acperadr  the value for IF_WCS_10.ACPERADR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setAcperadr(String acperadr) {
		this.acperadr = acperadr == null ? null : acperadr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.ACPERADRDETAIL
	 * @return  the value of IF_WCS_10.ACPERADRDETAIL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getAcperadrdetail() {
		return acperadrdetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.ACPERADRDETAIL
	 * @param acperadrdetail  the value for IF_WCS_10.ACPERADRDETAIL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setAcperadrdetail(String acperadrdetail) {
		this.acperadrdetail = acperadrdetail == null ? null : acperadrdetail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.GDSNM
	 * @return  the value of IF_WCS_10.GDSNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getGdsnm() {
		return gdsnm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.GDSNM
	 * @param gdsnm  the value for IF_WCS_10.GDSNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setGdsnm(String gdsnm) {
		this.gdsnm = gdsnm == null ? null : gdsnm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.DLVMSGCONT
	 * @return  the value of IF_WCS_10.DLVMSGCONT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDlvmsgcont() {
		return dlvmsgcont;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.DLVMSGCONT
	 * @param dlvmsgcont  the value for IF_WCS_10.DLVMSGCONT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDlvmsgcont(String dlvmsgcont) {
		this.dlvmsgcont = dlvmsgcont == null ? null : dlvmsgcont.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.FARESCTCD
	 * @return  the value of IF_WCS_10.FARESCTCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getFaresctcd() {
		return faresctcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.FARESCTCD
	 * @param faresctcd  the value for IF_WCS_10.FARESCTCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setFaresctcd(String faresctcd) {
		this.faresctcd = faresctcd == null ? null : faresctcd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.DLVFARE
	 * @return  the value of IF_WCS_10.DLVFARE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getDlvfare() {
		return dlvfare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.DLVFARE
	 * @param dlvfare  the value for IF_WCS_10.DLVFARE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDlvfare(BigDecimal dlvfare) {
		this.dlvfare = dlvfare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.TOTCNT
	 * @return  the value of IF_WCS_10.TOTCNT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getTotcnt() {
		return totcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.TOTCNT
	 * @param totcnt  the value for IF_WCS_10.TOTCNT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTotcnt(BigDecimal totcnt) {
		this.totcnt = totcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.CCPNM
	 * @return  the value of IF_WCS_10.CCPNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCcpnm() {
		return ccpnm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.CCPNM
	 * @param ccpnm  the value for IF_WCS_10.CCPNM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCcpnm(String ccpnm) {
		this.ccpnm = ccpnm == null ? null : ccpnm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.CCPTEL
	 * @return  the value of IF_WCS_10.CCPTEL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCcptel() {
		return ccptel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.CCPTEL
	 * @param ccptel  the value for IF_WCS_10.CCPTEL
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCcptel(String ccptel) {
		this.ccptel = ccptel == null ? null : ccptel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.DLCNT
	 * @return  the value of IF_WCS_10.DLCNT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDlcnt() {
		return dlcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.DLCNT
	 * @param dlcnt  the value for IF_WCS_10.DLCNT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDlcnt(String dlcnt) {
		this.dlcnt = dlcnt == null ? null : dlcnt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.USTRTGSCTCD
	 * @return  the value of IF_WCS_10.USTRTGSCTCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getUstrtgsctcd() {
		return ustrtgsctcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.USTRTGSCTCD
	 * @param ustrtgsctcd  the value for IF_WCS_10.USTRTGSCTCD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setUstrtgsctcd(String ustrtgsctcd) {
		this.ustrtgsctcd = ustrtgsctcd == null ? null : ustrtgsctcd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.ORDSCT
	 * @return  the value of IF_WCS_10.ORDSCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getOrdsct() {
		return ordsct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.ORDSCT
	 * @param ordsct  the value for IF_WCS_10.ORDSCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setOrdsct(String ordsct) {
		this.ordsct = ordsct == null ? null : ordsct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SHPOKY
	 * @return  the value of IF_WCS_10.SHPOKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getShpoky() {
		return shpoky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SHPOKY
	 * @param shpoky  the value for IF_WCS_10.SHPOKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setShpoky(String shpoky) {
		this.shpoky = shpoky == null ? null : shpoky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SHPOIT
	 * @return  the value of IF_WCS_10.SHPOIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getShpoit() {
		return shpoit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SHPOIT
	 * @param shpoit  the value for IF_WCS_10.SHPOIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setShpoit(String shpoit) {
		this.shpoit = shpoit == null ? null : shpoit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.OWNRKY
	 * @return  the value of IF_WCS_10.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getOwnrky() {
		return ownrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.OWNRKY
	 * @param ownrky  the value for IF_WCS_10.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setOwnrky(String ownrky) {
		this.ownrky = ownrky == null ? null : ownrky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SKUKEY
	 * @return  the value of IF_WCS_10.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSkukey() {
		return skukey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SKUKEY
	 * @param skukey  the value for IF_WCS_10.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSkukey(String skukey) {
		this.skukey = skukey == null ? null : skukey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.CTNTYP
	 * @return  the value of IF_WCS_10.CTNTYP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCtntyp() {
		return ctntyp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.CTNTYP
	 * @param ctntyp  the value for IF_WCS_10.CTNTYP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCtntyp(String ctntyp) {
		this.ctntyp = ctntyp == null ? null : ctntyp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.QTTAOR
	 * @return  the value of IF_WCS_10.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQttaor() {
		return qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.QTTAOR
	 * @param qttaor  the value for IF_WCS_10.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQttaor(BigDecimal qttaor) {
		this.qttaor = qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.QTCOMP
	 * @return  the value of IF_WCS_10.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQtcomp() {
		return qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.QTCOMP
	 * @param qtcomp  the value for IF_WCS_10.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQtcomp(BigDecimal qtcomp) {
		this.qtcomp = qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.QTTRS
	 * @return  the value of IF_WCS_10.QTTRS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQttrs() {
		return qttrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.QTTRS
	 * @param qttrs  the value for IF_WCS_10.QTTRS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQttrs(BigDecimal qttrs) {
		this.qttrs = qttrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.CREDATE
	 * @return  the value of IF_WCS_10.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCredate() {
		return credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.CREDATE
	 * @param credate  the value for IF_WCS_10.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCredate(Date credate) {
		this.credate = credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.CREUSR
	 * @return  the value of IF_WCS_10.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCreusr() {
		return creusr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.CREUSR
	 * @param creusr  the value for IF_WCS_10.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCreusr(String creusr) {
		this.creusr = creusr == null ? null : creusr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.TRSFLG
	 * @return  the value of IF_WCS_10.TRSFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTrsflg() {
		return trsflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.TRSFLG
	 * @param trsflg  the value for IF_WCS_10.TRSFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTrsflg(String trsflg) {
		this.trsflg = trsflg == null ? null : trsflg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.TRSDATE
	 * @return  the value of IF_WCS_10.TRSDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getTrsdate() {
		return trsdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.TRSDATE
	 * @param trsdate  the value for IF_WCS_10.TRSDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTrsdate(Date trsdate) {
		this.trsdate = trsdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.REMARKS
	 * @return  the value of IF_WCS_10.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.REMARKS
	 * @param remarks  the value for IF_WCS_10.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.JOB_NO
	 * @return  the value of IF_WCS_10.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getJobNo() {
		return jobNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.JOB_NO
	 * @param jobNo  the value for IF_WCS_10.JOB_NO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setJobNo(String jobNo) {
		this.jobNo = jobNo == null ? null : jobNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.WK_STS
	 * @return  the value of IF_WCS_10.WK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getWkSts() {
		return wkSts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.WK_STS
	 * @param wkSts  the value for IF_WCS_10.WK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setWkSts(String wkSts) {
		this.wkSts = wkSts == null ? null : wkSts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.BCR_POS
	 * @return  the value of IF_WCS_10.BCR_POS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBcrPos() {
		return bcrPos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.BCR_POS
	 * @param bcrPos  the value for IF_WCS_10.BCR_POS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBcrPos(String bcrPos) {
		this.bcrPos = bcrPos == null ? null : bcrPos.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.SKU_WEIGHT
	 * @return  the value of IF_WCS_10.SKU_WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getSkuWeight() {
		return skuWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.SKU_WEIGHT
	 * @param skuWeight  the value for IF_WCS_10.SKU_WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSkuWeight(BigDecimal skuWeight) {
		this.skuWeight = skuWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.LABEL_STS
	 * @return  the value of IF_WCS_10.LABEL_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLabelSts() {
		return labelSts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.LABEL_STS
	 * @param labelSts  the value for IF_WCS_10.LABEL_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLabelSts(String labelSts) {
		this.labelSts = labelSts == null ? null : labelSts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.TEST_STS
	 * @return  the value of IF_WCS_10.TEST_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTestSts() {
		return testSts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.TEST_STS
	 * @param testSts  the value for IF_WCS_10.TEST_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTestSts(String testSts) {
		this.testSts = testSts == null ? null : testSts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.QTY_MODIFY
	 * @return  the value of IF_WCS_10.QTY_MODIFY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getQtyModify() {
		return qtyModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.QTY_MODIFY
	 * @param qtyModify  the value for IF_WCS_10.QTY_MODIFY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQtyModify(String qtyModify) {
		this.qtyModify = qtyModify == null ? null : qtyModify.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.TEST_DATE
	 * @return  the value of IF_WCS_10.TEST_DATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getTestDate() {
		return testDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.TEST_DATE
	 * @param testDate  the value for IF_WCS_10.TEST_DATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.TEST_USER
	 * @return  the value of IF_WCS_10.TEST_USER
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTestUser() {
		return testUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.TEST_USER
	 * @param testUser  the value for IF_WCS_10.TEST_USER
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTestUser(String testUser) {
		this.testUser = testUser == null ? null : testUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.CHNTYP
	 * @return  the value of IF_WCS_10.CHNTYP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getChntyp() {
		return chntyp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.CHNTYP
	 * @param chntyp  the value for IF_WCS_10.CHNTYP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setChntyp(String chntyp) {
		this.chntyp = chntyp == null ? null : chntyp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.CHNCTN
	 * @return  the value of IF_WCS_10.CHNCTN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getChnctn() {
		return chnctn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.CHNCTN
	 * @param chnctn  the value for IF_WCS_10.CHNCTN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setChnctn(String chnctn) {
		this.chnctn = chnctn == null ? null : chnctn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.MODIFY_DTM
	 * @return  the value of IF_WCS_10.MODIFY_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getModifyDtm() {
		return modifyDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.MODIFY_DTM
	 * @param modifyDtm  the value for IF_WCS_10.MODIFY_DTM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModifyDtm(Date modifyDtm) {
		this.modifyDtm = modifyDtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.MODIFY_USER
	 * @return  the value of IF_WCS_10.MODIFY_USER
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getModifyUser() {
		return modifyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.MODIFY_USER
	 * @param modifyUser  the value for IF_WCS_10.MODIFY_USER
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser == null ? null : modifyUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_10.INVNO_CNT
	 * @return  the value of IF_WCS_10.INVNO_CNT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Short getInvnoCnt() {
		return invnoCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_10.INVNO_CNT
	 * @param invnoCnt  the value for IF_WCS_10.INVNO_CNT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setInvnoCnt(Short invnoCnt) {
		this.invnoCnt = invnoCnt;
	}
}