package com.fnwcs.pda.app.model;

import java.util.Date;

public class IfWcs12 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_12.INVCNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String invcno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_12.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date credate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_12.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String creusr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_12.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String cmpflg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_12.CMPDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date cmpdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_12.CMPMSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String cmpmsg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_12.INVCNO
	 * @return  the value of IF_WCS_12.INVCNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getInvcno() {
		return invcno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_12.INVCNO
	 * @param invcno  the value for IF_WCS_12.INVCNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setInvcno(String invcno) {
		this.invcno = invcno == null ? null : invcno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_12.CREDATE
	 * @return  the value of IF_WCS_12.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCredate() {
		return credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_12.CREDATE
	 * @param credate  the value for IF_WCS_12.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCredate(Date credate) {
		this.credate = credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_12.CREUSR
	 * @return  the value of IF_WCS_12.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCreusr() {
		return creusr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_12.CREUSR
	 * @param creusr  the value for IF_WCS_12.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCreusr(String creusr) {
		this.creusr = creusr == null ? null : creusr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_12.CMPFLG
	 * @return  the value of IF_WCS_12.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCmpflg() {
		return cmpflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_12.CMPFLG
	 * @param cmpflg  the value for IF_WCS_12.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpflg(String cmpflg) {
		this.cmpflg = cmpflg == null ? null : cmpflg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_12.CMPDATE
	 * @return  the value of IF_WCS_12.CMPDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCmpdate() {
		return cmpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_12.CMPDATE
	 * @param cmpdate  the value for IF_WCS_12.CMPDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpdate(Date cmpdate) {
		this.cmpdate = cmpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_12.CMPMSG
	 * @return  the value of IF_WCS_12.CMPMSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCmpmsg() {
		return cmpmsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_12.CMPMSG
	 * @param cmpmsg  the value for IF_WCS_12.CMPMSG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpmsg(String cmpmsg) {
		this.cmpmsg = cmpmsg == null ? null : cmpmsg.trim();
	}
}