package com.fnwcs.pda.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class IfWcs16 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String taskky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.TASKIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String taskit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.CRC_LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String crcLoct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String skukey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String desc01;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qttaor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qtcomp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.QTTRS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qttrs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.COMPYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String compyn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date credate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String creusr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String cmpflg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_16.CMPDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date cmpdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.TASKKY
	 * @return  the value of IF_WCS_16.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTaskky() {
		return taskky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.TASKKY
	 * @param taskky  the value for IF_WCS_16.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTaskky(String taskky) {
		this.taskky = taskky == null ? null : taskky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.TASKIT
	 * @return  the value of IF_WCS_16.TASKIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTaskit() {
		return taskit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.TASKIT
	 * @param taskit  the value for IF_WCS_16.TASKIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTaskit(String taskit) {
		this.taskit = taskit == null ? null : taskit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.CRC_LOCT
	 * @return  the value of IF_WCS_16.CRC_LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCrcLoct() {
		return crcLoct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.CRC_LOCT
	 * @param crcLoct  the value for IF_WCS_16.CRC_LOCT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCrcLoct(String crcLoct) {
		this.crcLoct = crcLoct == null ? null : crcLoct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.SKUKEY
	 * @return  the value of IF_WCS_16.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSkukey() {
		return skukey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.SKUKEY
	 * @param skukey  the value for IF_WCS_16.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSkukey(String skukey) {
		this.skukey = skukey == null ? null : skukey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.DESC01
	 * @return  the value of IF_WCS_16.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDesc01() {
		return desc01;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.DESC01
	 * @param desc01  the value for IF_WCS_16.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDesc01(String desc01) {
		this.desc01 = desc01 == null ? null : desc01.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.QTTAOR
	 * @return  the value of IF_WCS_16.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQttaor() {
		return qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.QTTAOR
	 * @param qttaor  the value for IF_WCS_16.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQttaor(BigDecimal qttaor) {
		this.qttaor = qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.QTCOMP
	 * @return  the value of IF_WCS_16.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQtcomp() {
		return qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.QTCOMP
	 * @param qtcomp  the value for IF_WCS_16.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQtcomp(BigDecimal qtcomp) {
		this.qtcomp = qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.QTTRS
	 * @return  the value of IF_WCS_16.QTTRS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQttrs() {
		return qttrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.QTTRS
	 * @param qttrs  the value for IF_WCS_16.QTTRS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQttrs(BigDecimal qttrs) {
		this.qttrs = qttrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.COMPYN
	 * @return  the value of IF_WCS_16.COMPYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCompyn() {
		return compyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.COMPYN
	 * @param compyn  the value for IF_WCS_16.COMPYN
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCompyn(String compyn) {
		this.compyn = compyn == null ? null : compyn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.CREDATE
	 * @return  the value of IF_WCS_16.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCredate() {
		return credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.CREDATE
	 * @param credate  the value for IF_WCS_16.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCredate(Date credate) {
		this.credate = credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.CREUSR
	 * @return  the value of IF_WCS_16.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCreusr() {
		return creusr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.CREUSR
	 * @param creusr  the value for IF_WCS_16.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCreusr(String creusr) {
		this.creusr = creusr == null ? null : creusr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.CMPFLG
	 * @return  the value of IF_WCS_16.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCmpflg() {
		return cmpflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.CMPFLG
	 * @param cmpflg  the value for IF_WCS_16.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpflg(String cmpflg) {
		this.cmpflg = cmpflg == null ? null : cmpflg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_16.CMPDATE
	 * @return  the value of IF_WCS_16.CMPDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCmpdate() {
		return cmpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_16.CMPDATE
	 * @param cmpdate  the value for IF_WCS_16.CMPDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpdate(Date cmpdate) {
		this.cmpdate = cmpdate;
	}
}