package com.fnwcs.pda.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class IfWcs15 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String taskky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.TASKIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String taskit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.TASKTY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String taskty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ownrky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String skukey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.LOCAFR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locafr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.LOCATO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qttaor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qtcomp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date credate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String creusr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.QTYCMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qtycmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_15.WK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String wkSts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.TASKKY
	 * @return  the value of IF_WCS_15.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTaskky() {
		return taskky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.TASKKY
	 * @param taskky  the value for IF_WCS_15.TASKKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTaskky(String taskky) {
		this.taskky = taskky == null ? null : taskky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.TASKIT
	 * @return  the value of IF_WCS_15.TASKIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTaskit() {
		return taskit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.TASKIT
	 * @param taskit  the value for IF_WCS_15.TASKIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTaskit(String taskit) {
		this.taskit = taskit == null ? null : taskit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.TASKTY
	 * @return  the value of IF_WCS_15.TASKTY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getTaskty() {
		return taskty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.TASKTY
	 * @param taskty  the value for IF_WCS_15.TASKTY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setTaskty(String taskty) {
		this.taskty = taskty == null ? null : taskty.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.OWNRKY
	 * @return  the value of IF_WCS_15.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getOwnrky() {
		return ownrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.OWNRKY
	 * @param ownrky  the value for IF_WCS_15.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setOwnrky(String ownrky) {
		this.ownrky = ownrky == null ? null : ownrky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.SKUKEY
	 * @return  the value of IF_WCS_15.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSkukey() {
		return skukey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.SKUKEY
	 * @param skukey  the value for IF_WCS_15.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSkukey(String skukey) {
		this.skukey = skukey == null ? null : skukey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.LOCAFR
	 * @return  the value of IF_WCS_15.LOCAFR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocafr() {
		return locafr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.LOCAFR
	 * @param locafr  the value for IF_WCS_15.LOCAFR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocafr(String locafr) {
		this.locafr = locafr == null ? null : locafr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.LOCATO
	 * @return  the value of IF_WCS_15.LOCATO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocato() {
		return locato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.LOCATO
	 * @param locato  the value for IF_WCS_15.LOCATO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocato(String locato) {
		this.locato = locato == null ? null : locato.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.QTTAOR
	 * @return  the value of IF_WCS_15.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQttaor() {
		return qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.QTTAOR
	 * @param qttaor  the value for IF_WCS_15.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQttaor(BigDecimal qttaor) {
		this.qttaor = qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.QTCOMP
	 * @return  the value of IF_WCS_15.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQtcomp() {
		return qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.QTCOMP
	 * @param qtcomp  the value for IF_WCS_15.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQtcomp(BigDecimal qtcomp) {
		this.qtcomp = qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.CREDATE
	 * @return  the value of IF_WCS_15.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCredate() {
		return credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.CREDATE
	 * @param credate  the value for IF_WCS_15.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCredate(Date credate) {
		this.credate = credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.CREUSR
	 * @return  the value of IF_WCS_15.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCreusr() {
		return creusr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.CREUSR
	 * @param creusr  the value for IF_WCS_15.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCreusr(String creusr) {
		this.creusr = creusr == null ? null : creusr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.QTYCMP
	 * @return  the value of IF_WCS_15.QTYCMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQtycmp() {
		return qtycmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.QTYCMP
	 * @param qtycmp  the value for IF_WCS_15.QTYCMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQtycmp(BigDecimal qtycmp) {
		this.qtycmp = qtycmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_15.WK_STS
	 * @return  the value of IF_WCS_15.WK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getWkSts() {
		return wkSts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_15.WK_STS
	 * @param wkSts  the value for IF_WCS_15.WK_STS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setWkSts(String wkSts) {
		this.wkSts = wkSts == null ? null : wkSts.trim();
	}
}