package com.fnwcs.pda.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class IfWcs01 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ownrky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String skukey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String desc01;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.DESC02
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String desc02;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.BARCOD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String barcod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.LENGTH
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal length;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.WIDTHW
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal widthw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.HEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal height;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.BXIPSU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal bxipsu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.PLIPSU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal plipsu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date credate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String creusr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_01.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.OWNRKY
	 * @return  the value of IF_WCS_01.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getOwnrky() {
		return ownrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.OWNRKY
	 * @param ownrky  the value for IF_WCS_01.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setOwnrky(String ownrky) {
		this.ownrky = ownrky == null ? null : ownrky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.SKUKEY
	 * @return  the value of IF_WCS_01.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSkukey() {
		return skukey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.SKUKEY
	 * @param skukey  the value for IF_WCS_01.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSkukey(String skukey) {
		this.skukey = skukey == null ? null : skukey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.DESC01
	 * @return  the value of IF_WCS_01.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDesc01() {
		return desc01;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.DESC01
	 * @param desc01  the value for IF_WCS_01.DESC01
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDesc01(String desc01) {
		this.desc01 = desc01 == null ? null : desc01.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.DESC02
	 * @return  the value of IF_WCS_01.DESC02
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getDesc02() {
		return desc02;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.DESC02
	 * @param desc02  the value for IF_WCS_01.DESC02
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setDesc02(String desc02) {
		this.desc02 = desc02 == null ? null : desc02.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.BARCOD
	 * @return  the value of IF_WCS_01.BARCOD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getBarcod() {
		return barcod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.BARCOD
	 * @param barcod  the value for IF_WCS_01.BARCOD
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBarcod(String barcod) {
		this.barcod = barcod == null ? null : barcod.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.WEIGHT
	 * @return  the value of IF_WCS_01.WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.WEIGHT
	 * @param weight  the value for IF_WCS_01.WEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.LENGTH
	 * @return  the value of IF_WCS_01.LENGTH
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getLength() {
		return length;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.LENGTH
	 * @param length  the value for IF_WCS_01.LENGTH
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLength(BigDecimal length) {
		this.length = length;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.WIDTHW
	 * @return  the value of IF_WCS_01.WIDTHW
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getWidthw() {
		return widthw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.WIDTHW
	 * @param widthw  the value for IF_WCS_01.WIDTHW
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setWidthw(BigDecimal widthw) {
		this.widthw = widthw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.HEIGHT
	 * @return  the value of IF_WCS_01.HEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.HEIGHT
	 * @param height  the value for IF_WCS_01.HEIGHT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.BXIPSU
	 * @return  the value of IF_WCS_01.BXIPSU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getBxipsu() {
		return bxipsu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.BXIPSU
	 * @param bxipsu  the value for IF_WCS_01.BXIPSU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setBxipsu(BigDecimal bxipsu) {
		this.bxipsu = bxipsu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.PLIPSU
	 * @return  the value of IF_WCS_01.PLIPSU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getPlipsu() {
		return plipsu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.PLIPSU
	 * @param plipsu  the value for IF_WCS_01.PLIPSU
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setPlipsu(BigDecimal plipsu) {
		this.plipsu = plipsu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.CREDATE
	 * @return  the value of IF_WCS_01.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCredate() {
		return credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.CREDATE
	 * @param credate  the value for IF_WCS_01.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCredate(Date credate) {
		this.credate = credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.CREUSR
	 * @return  the value of IF_WCS_01.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCreusr() {
		return creusr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.CREUSR
	 * @param creusr  the value for IF_WCS_01.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCreusr(String creusr) {
		this.creusr = creusr == null ? null : creusr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_01.REMARKS
	 * @return  the value of IF_WCS_01.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_01.REMARKS
	 * @param remarks  the value for IF_WCS_01.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}
}