package com.fnwcs.pda.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class IfWcs11 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.INVCNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String invcno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.LOCASR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String locasr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.SHPDAT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String shpdat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.STKNUM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String stknum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.STKSEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Short stkseq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.SHPOKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String shpoky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.SHPOIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String shpoit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ownrky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String skukey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.CTNTYP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String ctntyp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qttaor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qtcomp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.QTTRS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private BigDecimal qttrs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private Date credate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String creusr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String cmpflg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.CMPDAT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String cmpdat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IF_WCS_11.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.INVCNO
	 * @return  the value of IF_WCS_11.INVCNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getInvcno() {
		return invcno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.INVCNO
	 * @param invcno  the value for IF_WCS_11.INVCNO
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setInvcno(String invcno) {
		this.invcno = invcno == null ? null : invcno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.LOCASR
	 * @return  the value of IF_WCS_11.LOCASR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getLocasr() {
		return locasr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.LOCASR
	 * @param locasr  the value for IF_WCS_11.LOCASR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setLocasr(String locasr) {
		this.locasr = locasr == null ? null : locasr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.SHPDAT
	 * @return  the value of IF_WCS_11.SHPDAT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getShpdat() {
		return shpdat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.SHPDAT
	 * @param shpdat  the value for IF_WCS_11.SHPDAT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setShpdat(String shpdat) {
		this.shpdat = shpdat == null ? null : shpdat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.STKNUM
	 * @return  the value of IF_WCS_11.STKNUM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getStknum() {
		return stknum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.STKNUM
	 * @param stknum  the value for IF_WCS_11.STKNUM
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setStknum(String stknum) {
		this.stknum = stknum == null ? null : stknum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.STKSEQ
	 * @return  the value of IF_WCS_11.STKSEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Short getStkseq() {
		return stkseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.STKSEQ
	 * @param stkseq  the value for IF_WCS_11.STKSEQ
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setStkseq(Short stkseq) {
		this.stkseq = stkseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.SHPOKY
	 * @return  the value of IF_WCS_11.SHPOKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getShpoky() {
		return shpoky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.SHPOKY
	 * @param shpoky  the value for IF_WCS_11.SHPOKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setShpoky(String shpoky) {
		this.shpoky = shpoky == null ? null : shpoky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.SHPOIT
	 * @return  the value of IF_WCS_11.SHPOIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getShpoit() {
		return shpoit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.SHPOIT
	 * @param shpoit  the value for IF_WCS_11.SHPOIT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setShpoit(String shpoit) {
		this.shpoit = shpoit == null ? null : shpoit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.OWNRKY
	 * @return  the value of IF_WCS_11.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getOwnrky() {
		return ownrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.OWNRKY
	 * @param ownrky  the value for IF_WCS_11.OWNRKY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setOwnrky(String ownrky) {
		this.ownrky = ownrky == null ? null : ownrky.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.SKUKEY
	 * @return  the value of IF_WCS_11.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getSkukey() {
		return skukey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.SKUKEY
	 * @param skukey  the value for IF_WCS_11.SKUKEY
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setSkukey(String skukey) {
		this.skukey = skukey == null ? null : skukey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.CTNTYP
	 * @return  the value of IF_WCS_11.CTNTYP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCtntyp() {
		return ctntyp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.CTNTYP
	 * @param ctntyp  the value for IF_WCS_11.CTNTYP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCtntyp(String ctntyp) {
		this.ctntyp = ctntyp == null ? null : ctntyp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.QTTAOR
	 * @return  the value of IF_WCS_11.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQttaor() {
		return qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.QTTAOR
	 * @param qttaor  the value for IF_WCS_11.QTTAOR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQttaor(BigDecimal qttaor) {
		this.qttaor = qttaor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.QTCOMP
	 * @return  the value of IF_WCS_11.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQtcomp() {
		return qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.QTCOMP
	 * @param qtcomp  the value for IF_WCS_11.QTCOMP
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQtcomp(BigDecimal qtcomp) {
		this.qtcomp = qtcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.QTTRS
	 * @return  the value of IF_WCS_11.QTTRS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public BigDecimal getQttrs() {
		return qttrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.QTTRS
	 * @param qttrs  the value for IF_WCS_11.QTTRS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setQttrs(BigDecimal qttrs) {
		this.qttrs = qttrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.CREDATE
	 * @return  the value of IF_WCS_11.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public Date getCredate() {
		return credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.CREDATE
	 * @param credate  the value for IF_WCS_11.CREDATE
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCredate(Date credate) {
		this.credate = credate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.CREUSR
	 * @return  the value of IF_WCS_11.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCreusr() {
		return creusr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.CREUSR
	 * @param creusr  the value for IF_WCS_11.CREUSR
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCreusr(String creusr) {
		this.creusr = creusr == null ? null : creusr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.CMPFLG
	 * @return  the value of IF_WCS_11.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCmpflg() {
		return cmpflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.CMPFLG
	 * @param cmpflg  the value for IF_WCS_11.CMPFLG
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpflg(String cmpflg) {
		this.cmpflg = cmpflg == null ? null : cmpflg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.CMPDAT
	 * @return  the value of IF_WCS_11.CMPDAT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getCmpdat() {
		return cmpdat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.CMPDAT
	 * @param cmpdat  the value for IF_WCS_11.CMPDAT
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setCmpdat(String cmpdat) {
		this.cmpdat = cmpdat == null ? null : cmpdat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IF_WCS_11.REMARKS
	 * @return  the value of IF_WCS_11.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IF_WCS_11.REMARKS
	 * @param remarks  the value for IF_WCS_11.REMARKS
	 * @mbg.generated  Wed Aug 11 12:35:31 KST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}
}